# flint zsh integration. Generated by `flint init zsh`; source it, don't edit
# the copy in your dotfiles by hand — re-run `flint init zsh` after upgrades.

[[ -o interactive ]] || return 0
(( $+commands[flint] )) || return 0

autoload -Uz add-zsh-hook add-zle-hook-widget
zmodload zsh/datetime 2>/dev/null
# On a minimal startup that never touches a zle builtin (e.g. no bindkey in
# any rc file before this point) zsh/zle isn't loaded yet, and
# add-zle-hook-widget silently no-ops without it.
zmodload zsh/zle 2>/dev/null

typeset -g _flint_prev_cmd=""
typeset -g _flint_cur_cmd=""
typeset -g _flint_cmd_start=""
typeset -g _flint_accepted=0
typeset -g _flint_last_buffer=""
typeset -g FLINT_SUGGEST_FG="${FLINT_SUGGEST_FG:-8}"

command flint sync >/dev/null 2>&1 &!

_flint_preexec() {
  _flint_cur_cmd="$1"
  _flint_cmd_start="$EPOCHREALTIME"
}
add-zsh-hook preexec _flint_preexec

# Exit code must be captured as the very first thing this function does —
# any command run before this line would overwrite $?.
_flint_precmd() {
  local exit_code=$?
  POSTDISPLAY=""
  if [[ -n $_flint_cur_cmd ]]; then
    local duration_ms=0
    if [[ -n $_flint_cmd_start && -n $EPOCHREALTIME ]]; then
      duration_ms=$(( (EPOCHREALTIME - _flint_cmd_start) * 1000 ))
      duration_ms=${duration_ms%%.*}
    fi
    local accepted_flag=0
    (( _flint_accepted )) && accepted_flag=1
    command flint record \
      --command "$_flint_cur_cmd" \
      --prev "$_flint_prev_cmd" \
      --cwd "$PWD" \
      --exit-code "$exit_code" \
      --duration-ms "$duration_ms" \
      --accepted "$accepted_flag" \
      >/dev/null 2>&1 &!
    _flint_prev_cmd="$_flint_cur_cmd"
  fi
  _flint_cur_cmd=""
  _flint_cmd_start=""
  _flint_accepted=0
  _flint_last_buffer=""
}
add-zsh-hook precmd _flint_precmd

_flint_update_suggestion() {
  [[ $BUFFER == $_flint_last_buffer ]] && return
  _flint_last_buffer=$BUFFER
  # region_highlight is an array shared with other plugins (e.g.
  # zsh-syntax-highlighting) — it only ever accumulates entries, so our own
  # previous span (from the last, now-stale, buffer) must be stripped every
  # time or it lingers over real text once the buffer changes or the
  # suggestion is accepted, rendering already-typed characters dim.
  region_highlight=("${(@)region_highlight:#*fg=$FLINT_SUGGEST_FG}")
  if [[ -z $BUFFER ]]; then
    POSTDISPLAY=""
    return
  fi
  local suggestion
  suggestion=$(command flint suggest --prefix "$BUFFER" --cwd "$PWD" --prev "$_flint_prev_cmd" 2>/dev/null)
  if [[ -n $suggestion ]]; then
    POSTDISPLAY="$suggestion"
    # Appended after any existing highlight entries so that plugins like
    # zsh-syntax-highlighting (which rebuild region_highlight from scratch
    # on redraw) must run *before* flint is sourced, or this gets clobbered.
    region_highlight+=("${#BUFFER} $(( ${#BUFFER} + ${#suggestion} )) fg=$FLINT_SUGGEST_FG")
  else
    POSTDISPLAY=""
  fi
}
add-zle-hook-widget line-pre-redraw _flint_update_suggestion

_flint_accept_or_forward_char() {
  if [[ -n $POSTDISPLAY && $CURSOR -eq ${#BUFFER} ]]; then
    BUFFER+="$POSTDISPLAY"
    CURSOR=${#BUFFER}
    POSTDISPLAY=""
    _flint_accepted=1
  else
    zle .forward-char
  fi
}
zle -N _flint_accept_or_forward_char

_flint_accept_or_end_of_line() {
  # Only treat End as "accept" when the cursor is already at the end of
  # what's actually typed — otherwise a mid-buffer edit (e.g. after
  # Left-arrow, or a history recall that didn't move the cursor) would jump
  # to the end AND silently swallow the ghost suggestion instead of just
  # moving to the real end of line.
  if [[ -n $POSTDISPLAY && $CURSOR -eq ${#BUFFER} ]]; then
    BUFFER+="$POSTDISPLAY"
    CURSOR=${#BUFFER}
    POSTDISPLAY=""
    _flint_accepted=1
  else
    zle .end-of-line
  fi
}
zle -N _flint_accept_or_end_of_line

_flint_accept_word() {
  if [[ -n $POSTDISPLAY && $CURSOR -eq ${#BUFFER} ]]; then
    local rest="$POSTDISPLAY"
    if [[ $rest =~ '^([[:space:]]*[^[:space:]]+)' ]]; then
      local word="$match[1]"
      BUFFER+="$word"
      POSTDISPLAY="${rest#$word}"
      CURSOR=${#BUFFER}
      [[ -z $POSTDISPLAY ]] && _flint_accepted=1
    fi
  else
    zle .forward-word
  fi
}
zle -N _flint_accept_word

_flint_history_search() {
  zle -I
  local selected
  selected=$(command flint search --query "$BUFFER" --cwd "$PWD" < /dev/tty)
  if [[ -n $selected ]]; then
    BUFFER="$selected"
    CURSOR=${#BUFFER}
  fi
  zle reset-prompt
}
zle -N _flint_history_search

bindkey '^[[C' _flint_accept_or_forward_char   # Right arrow
bindkey '^E' _flint_accept_or_end_of_line      # End / Ctrl-E
bindkey '^[f' _flint_accept_word               # Alt-f
bindkey '^[[1;3C' _flint_accept_word           # Alt-Right
bindkey '^R' _flint_history_search
